---
- package:
    name:
      - fontconfig
    state: present
    update_cache: true
- package:
    name:
      - openjdk-17-jre
    state: present
  when: ansible_distribution == "Debian" and ansible_distribution_major_version < "13"
- package:
    name:
      - openjdk-21-jre
    state: present
  when: (ansible_distribution == "Debian" and ansible_distribution_major_version == "13") or ansible_distribution == "Ubuntu"
- find:
    paths: /var/tmp/target/debian
    file_type: file
    patterns: "*.deb"
  register: package_list
- assert:
    that:
      - package_list.matched == 1
- apt:
    deb: "{{ package_list.files[0].path }}"
